// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGkz9wdMHMu5huAyqJJ_lIPW5n9e5Fb6A',
    appId: '1:546129770829:web:32f444772aaa5df7f4df04',
    messagingSenderId: '546129770829',
    projectId: 'survey-app-e4a27',
    authDomain: 'survey-app-e4a27.firebaseapp.com',
    storageBucket: 'survey-app-e4a27.firebasestorage.app',
    measurementId: 'G-4XP2TEMT9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDM-Zc4zGyxsJOotVFY7A0sQ7k4APSK6M',
    appId: '1:546129770829:android:bfd4af08196ddf14f4df04',
    messagingSenderId: '546129770829',
    projectId: 'survey-app-e4a27',
    storageBucket: 'survey-app-e4a27.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGkz9wdMHMu5huAyqJJ_lIPW5n9e5Fb6A',
    appId: '1:546129770829:web:0f5cf2f698cbab56f4df04',
    messagingSenderId: '546129770829',
    projectId: 'survey-app-e4a27',
    authDomain: 'survey-app-e4a27.firebaseapp.com',
    storageBucket: 'survey-app-e4a27.firebasestorage.app',
    measurementId: 'G-DZ7V54YHY5',
  );
}
